AWSTemplateFormatVersion: "2010-09-09"
Description: "aws glue job, glue trigger, glue workflow, glue crawler, s3 buckets creation test"

Resources:
  Yelpinbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'yelp-input-data'